INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
ERROR:root:Terjadi kesalahan: Message: element click intercepted: Element <div class="x8t9es0 x1fvot60 xxio538 x1heor9g xuxw1ft x6ikm8r x10wlt62 xlyipyv x1h4wwuj x1pd3egz xeuugli">...</div> is not clickable at point (1810, 36). Other element would receive the click: <div class="x1qjc9v5 x9f619 x78zum5 xdt5ytf x1nhvcw1 xg6iff7 xurb0ha x1sxyh0 x1l90r2v" data-visualcompletion="ignore" style="padding-top: 187px;">...</div>
  (Session info: chrome=125.0.6422.141)
Stacktrace:
#0 0x562ea20a4e3a <unknown>
#1 0x562ea1d8e45c <unknown>
#2 0x562ea1de1336 <unknown>
#3 0x562ea1ddf176 <unknown>
#4 0x562ea1ddcb57 <unknown>
#5 0x562ea1ddb97c <unknown>
#6 0x562ea1dcf0ff <unknown>
#7 0x562ea1dfd4b2 <unknown>
#8 0x562ea1dcea79 <unknown>
#9 0x562ea1dfd67e <unknown>
#10 0x562ea1e1c2cc <unknown>
#11 0x562ea1dfd253 <unknown>
#12 0x562ea1dcd1c7 <unknown>
#13 0x562ea1dcdb3e <unknown>
#14 0x562ea206b27b <unknown>
#15 0x562ea206f327 <unknown>
#16 0x562ea2057dae <unknown>
#17 0x562ea206fdf2 <unknown>
#18 0x562ea203c74f <unknown>
#19 0x562ea2094128 <unknown>
#20 0x562ea20942fb <unknown>
#21 0x562ea20a3f6c <unknown>
#22 0x7f5738675ac3 <unknown>

Traceback (most recent call last):
  File "/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py", line 50, in <module>
    second_export.click()
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="x8t9es0 x1fvot60 xxio538 x1heor9g xuxw1ft x6ikm8r x10wlt62 xlyipyv x1h4wwuj x1pd3egz xeuugli">...</div> is not clickable at point (1810, 36). Other element would receive the click: <div class="x1qjc9v5 x9f619 x78zum5 xdt5ytf x1nhvcw1 xg6iff7 xurb0ha x1sxyh0 x1l90r2v" data-visualcompletion="ignore" style="padding-top: 187px;">...</div>
  (Session info: chrome=125.0.6422.141)
Stacktrace:
#0 0x562ea20a4e3a <unknown>
#1 0x562ea1d8e45c <unknown>
#2 0x562ea1de1336 <unknown>
#3 0x562ea1ddf176 <unknown>
#4 0x562ea1ddcb57 <unknown>
#5 0x562ea1ddb97c <unknown>
#6 0x562ea1dcf0ff <unknown>
#7 0x562ea1dfd4b2 <unknown>
#8 0x562ea1dcea79 <unknown>
#9 0x562ea1dfd67e <unknown>
#10 0x562ea1e1c2cc <unknown>
#11 0x562ea1dfd253 <unknown>
#12 0x562ea1dcd1c7 <unknown>
#13 0x562ea1dcdb3e <unknown>
#14 0x562ea206b27b <unknown>
#15 0x562ea206f327 <unknown>
#16 0x562ea2057dae <unknown>
#17 0x562ea206fdf2 <unknown>
#18 0x562ea203c74f <unknown>
#19 0x562ea2094128 <unknown>
#20 0x562ea20942fb <unknown>
#21 0x562ea20a3f6c <unknown>
#22 0x7f5738675ac3 <unknown>


INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
ERROR:root:Terjadi kesalahan: File tidak berhasil diunduh dalam batas waktu yang ditentukan.
Traceback (most recent call last):
  File "/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py", line 57, in <module>
    raise FileNotFoundError("File tidak berhasil diunduh dalam batas waktu yang ditentukan.")
FileNotFoundError: File tidak berhasil diunduh dalam batas waktu yang ditentukan.

INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
ERROR:root:Terjadi kesalahan: Message: 
Stacktrace:
#0 0x561adbd82e3a <unknown>
#1 0x561adba6c45c <unknown>
#2 0x561adbab85b5 <unknown>
#3 0x561adbab8671 <unknown>
#4 0x561adbafcf14 <unknown>
#5 0x561adbadb4dd <unknown>
#6 0x561adbafa2cc <unknown>
#7 0x561adbadb253 <unknown>
#8 0x561adbaab1c7 <unknown>
#9 0x561adbaabb3e <unknown>
#10 0x561adbd4927b <unknown>
#11 0x561adbd4d327 <unknown>
#12 0x561adbd35dae <unknown>
#13 0x561adbd4ddf2 <unknown>
#14 0x561adbd1a74f <unknown>
#15 0x561adbd72128 <unknown>
#16 0x561adbd722fb <unknown>
#17 0x561adbd81f6c <unknown>
#18 0x7f4425ca3ac3 <unknown>

Traceback (most recent call last):
  File "/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py", line 48, in <module>
    second_export = wait.until(EC.presence_of_element_located((By.XPATH, "div[contains(text(), 'Export')]")))
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x561adbd82e3a <unknown>
#1 0x561adba6c45c <unknown>
#2 0x561adbab85b5 <unknown>
#3 0x561adbab8671 <unknown>
#4 0x561adbafcf14 <unknown>
#5 0x561adbadb4dd <unknown>
#6 0x561adbafa2cc <unknown>
#7 0x561adbadb253 <unknown>
#8 0x561adbaab1c7 <unknown>
#9 0x561adbaabb3e <unknown>
#10 0x561adbd4927b <unknown>
#11 0x561adbd4d327 <unknown>
#12 0x561adbd35dae <unknown>
#13 0x561adbd4ddf2 <unknown>
#14 0x561adbd1a74f <unknown>
#15 0x561adbd72128 <unknown>
#16 0x561adbd722fb <unknown>
#17 0x561adbd81f6c <unknown>
#18 0x7f4425ca3ac3 <unknown>


INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
ERROR:root:Terjadi kesalahan: Message: element click intercepted: Element <div aria-busy="false" class="x1i10hfl xjqpnuy xa49m3k xqeqjp1 x2hbi6w x972fbf xcfux6l x1qhh985 xm0m39n x9f619 x1ypdohk xe8uvvx xdj266r x11i5rnm xat24cr x1mh8g0r x2lwn1j xeuugli x16tdsg8 xggy1nq x1ja2u2z x1t137rt x6s0dn4 x1ejq31n xd10rxx x1sy0etr x17r0tee x3nfvp2 xdl72j9 x1q0g3np x2lah0s x193iq5w x1n2onr6 x1hl2dhg x87ps6o xxymvpz xlh3980 xvmahel x1lku1pv xhk9q7s x1otrzb0 x1i1ezom x1o6z2jb xo1l8bm x108nfp6 xas4zb2 x1y1aw1k xwib8y2 x1pi30zi x1ye3gou" role="button" tabindex="0" data-auto-logging-id="f3d7efdb6b041f8" id="js_i2">...</div> is not clickable at point (1801, 36). Other element would receive the click: <div class="x1qjc9v5 x9f619 x78zum5 xdt5ytf x1nhvcw1 xg6iff7 xurb0ha x1sxyh0 x1l90r2v" data-visualcompletion="ignore" style="padding-top: 187px;">...</div>
  (Session info: chrome=125.0.6422.141)
Stacktrace:
#0 0x564286bb0e3a <unknown>
#1 0x56428689a45c <unknown>
#2 0x5642868ed336 <unknown>
#3 0x5642868eb176 <unknown>
#4 0x5642868e8b57 <unknown>
#5 0x5642868e797c <unknown>
#6 0x5642868db0ff <unknown>
#7 0x5642869094b2 <unknown>
#8 0x5642868daa79 <unknown>
#9 0x56428690967e <unknown>
#10 0x5642869282cc <unknown>
#11 0x564286909253 <unknown>
#12 0x5642868d91c7 <unknown>
#13 0x5642868d9b3e <unknown>
#14 0x564286b7727b <unknown>
#15 0x564286b7b327 <unknown>
#16 0x564286b63dae <unknown>
#17 0x564286b7bdf2 <unknown>
#18 0x564286b4874f <unknown>
#19 0x564286ba0128 <unknown>
#20 0x564286ba02fb <unknown>
#21 0x564286baff6c <unknown>
#22 0x7f3441845ac3 <unknown>

Traceback (most recent call last):
  File "/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py", line 50, in <module>
    second_export.click()
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div aria-busy="false" class="x1i10hfl xjqpnuy xa49m3k xqeqjp1 x2hbi6w x972fbf xcfux6l x1qhh985 xm0m39n x9f619 x1ypdohk xe8uvvx xdj266r x11i5rnm xat24cr x1mh8g0r x2lwn1j xeuugli x16tdsg8 xggy1nq x1ja2u2z x1t137rt x6s0dn4 x1ejq31n xd10rxx x1sy0etr x17r0tee x3nfvp2 xdl72j9 x1q0g3np x2lah0s x193iq5w x1n2onr6 x1hl2dhg x87ps6o xxymvpz xlh3980 xvmahel x1lku1pv xhk9q7s x1otrzb0 x1i1ezom x1o6z2jb xo1l8bm x108nfp6 xas4zb2 x1y1aw1k xwib8y2 x1pi30zi x1ye3gou" role="button" tabindex="0" data-auto-logging-id="f3d7efdb6b041f8" id="js_i2">...</div> is not clickable at point (1801, 36). Other element would receive the click: <div class="x1qjc9v5 x9f619 x78zum5 xdt5ytf x1nhvcw1 xg6iff7 xurb0ha x1sxyh0 x1l90r2v" data-visualcompletion="ignore" style="padding-top: 187px;">...</div>
  (Session info: chrome=125.0.6422.141)
Stacktrace:
#0 0x564286bb0e3a <unknown>
#1 0x56428689a45c <unknown>
#2 0x5642868ed336 <unknown>
#3 0x5642868eb176 <unknown>
#4 0x5642868e8b57 <unknown>
#5 0x5642868e797c <unknown>
#6 0x5642868db0ff <unknown>
#7 0x5642869094b2 <unknown>
#8 0x5642868daa79 <unknown>
#9 0x56428690967e <unknown>
#10 0x5642869282cc <unknown>
#11 0x564286909253 <unknown>
#12 0x5642868d91c7 <unknown>
#13 0x5642868d9b3e <unknown>
#14 0x564286b7727b <unknown>
#15 0x564286b7b327 <unknown>
#16 0x564286b63dae <unknown>
#17 0x564286b7bdf2 <unknown>
#18 0x564286b4874f <unknown>
#19 0x564286ba0128 <unknown>
#20 0x564286ba02fb <unknown>
#21 0x564286baff6c <unknown>
#22 0x7f3441845ac3 <unknown>


INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
ERROR:root:Terjadi kesalahan: File tidak berhasil diunduh dalam batas waktu yang ditentukan.
Traceback (most recent call last):
  File "/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py", line 58, in <module>
    raise FileNotFoundError("File tidak berhasil diunduh dalam batas waktu yang ditentukan.")
FileNotFoundError: File tidak berhasil diunduh dalam batas waktu yang ditentukan.

INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
ERROR:root:Terjadi kesalahan: Message: unknown error: cannot connect to chrome at 127.0.0.1:50443
from chrome not reachable
Stacktrace:
#0 0x559a7b5f9e3a <unknown>
#1 0x559a7b2e32a1 <unknown>
#2 0x559a7b2cd96f <unknown>
#3 0x559a7b31d825 <unknown>
#4 0x559a7b3140b4 <unknown>
#5 0x559a7b35eb19 <unknown>
#6 0x559a7b352253 <unknown>
#7 0x559a7b3221c7 <unknown>
#8 0x559a7b322b3e <unknown>
#9 0x559a7b5c027b <unknown>
#10 0x559a7b5c4327 <unknown>
#11 0x559a7b5acdae <unknown>
#12 0x559a7b5c4df2 <unknown>
#13 0x559a7b59174f <unknown>
#14 0x559a7b5e9128 <unknown>
#15 0x559a7b5e92fb <unknown>
#16 0x559a7b5f8f6c <unknown>
#17 0x7f40cdd1eac3 <unknown>

Traceback (most recent call last):
  File "/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py", line 39, in <module>
    driver = uc.Chrome(options=options)
  File "/home/rajab/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 49, in __init__
    super().__init__(
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 54, in __init__
    super().__init__(
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/home/rajab/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:50443
from chrome not reachable
Stacktrace:
#0 0x559a7b5f9e3a <unknown>
#1 0x559a7b2e32a1 <unknown>
#2 0x559a7b2cd96f <unknown>
#3 0x559a7b31d825 <unknown>
#4 0x559a7b3140b4 <unknown>
#5 0x559a7b35eb19 <unknown>
#6 0x559a7b352253 <unknown>
#7 0x559a7b3221c7 <unknown>
#8 0x559a7b322b3e <unknown>
#9 0x559a7b5c027b <unknown>
#10 0x559a7b5c4327 <unknown>
#11 0x559a7b5acdae <unknown>
#12 0x559a7b5c4df2 <unknown>
#13 0x559a7b59174f <unknown>
#14 0x559a7b5e9128 <unknown>
#15 0x559a7b5e92fb <unknown>
#16 0x559a7b5f8f6c <unknown>
#17 0x7f40cdd1eac3 <unknown>


INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
ERROR:root:Terjadi kesalahan: Message: element click intercepted: Element <div class="x8t9es0 x1fvot60 xxio538 x1heor9g xuxw1ft x6ikm8r x10wlt62 xlyipyv x1h4wwuj x1pd3egz xeuugli">...</div> is not clickable at point (1811, 36). Other element would receive the click: <div class="x1qjc9v5 x9f619 x78zum5 xdt5ytf x1nhvcw1 xg6iff7 xurb0ha x1sxyh0 x1l90r2v" data-visualcompletion="ignore" style="padding-top: 187px;">...</div>
  (Session info: chrome=125.0.6422.141)
Stacktrace:
#0 0x5623eda9ee3a <unknown>
#1 0x5623ed78845c <unknown>
#2 0x5623ed7db336 <unknown>
#3 0x5623ed7d9176 <unknown>
#4 0x5623ed7d6b57 <unknown>
#5 0x5623ed7d597c <unknown>
#6 0x5623ed7c90ff <unknown>
#7 0x5623ed7f74b2 <unknown>
#8 0x5623ed7c8a79 <unknown>
#9 0x5623ed7f767e <unknown>
#10 0x5623ed8162cc <unknown>
#11 0x5623ed7f7253 <unknown>
#12 0x5623ed7c71c7 <unknown>
#13 0x5623ed7c7b3e <unknown>
#14 0x5623eda6527b <unknown>
#15 0x5623eda69327 <unknown>
#16 0x5623eda51dae <unknown>
#17 0x5623eda69df2 <unknown>
#18 0x5623eda3674f <unknown>
#19 0x5623eda8e128 <unknown>
#20 0x5623eda8e2fb <unknown>
#21 0x5623eda9df6c <unknown>
#22 0x7fcedb1eeac3 <unknown>

Traceback (most recent call last):
  File "/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py", line 51, in <module>
    second_export.click()
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="x8t9es0 x1fvot60 xxio538 x1heor9g xuxw1ft x6ikm8r x10wlt62 xlyipyv x1h4wwuj x1pd3egz xeuugli">...</div> is not clickable at point (1811, 36). Other element would receive the click: <div class="x1qjc9v5 x9f619 x78zum5 xdt5ytf x1nhvcw1 xg6iff7 xurb0ha x1sxyh0 x1l90r2v" data-visualcompletion="ignore" style="padding-top: 187px;">...</div>
  (Session info: chrome=125.0.6422.141)
Stacktrace:
#0 0x5623eda9ee3a <unknown>
#1 0x5623ed78845c <unknown>
#2 0x5623ed7db336 <unknown>
#3 0x5623ed7d9176 <unknown>
#4 0x5623ed7d6b57 <unknown>
#5 0x5623ed7d597c <unknown>
#6 0x5623ed7c90ff <unknown>
#7 0x5623ed7f74b2 <unknown>
#8 0x5623ed7c8a79 <unknown>
#9 0x5623ed7f767e <unknown>
#10 0x5623ed8162cc <unknown>
#11 0x5623ed7f7253 <unknown>
#12 0x5623ed7c71c7 <unknown>
#13 0x5623ed7c7b3e <unknown>
#14 0x5623eda6527b <unknown>
#15 0x5623eda69327 <unknown>
#16 0x5623eda51dae <unknown>
#17 0x5623eda69df2 <unknown>
#18 0x5623eda3674f <unknown>
#19 0x5623eda8e128 <unknown>
#20 0x5623eda8e2fb <unknown>
#21 0x5623eda9df6c <unknown>
#22 0x7fcedb1eeac3 <unknown>


INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
ERROR:root:Terjadi kesalahan: Message: element not interactable
  (Session info: chrome=125.0.6422.141)
Stacktrace:
#0 0x55b0e30a8e3a <unknown>
#1 0x55b0e2d922a1 <unknown>
#2 0x55b0e2ddf70f <unknown>
#3 0x55b0e2dd30ff <unknown>
#4 0x55b0e2e014b2 <unknown>
#5 0x55b0e2dd2a79 <unknown>
#6 0x55b0e2e0167e <unknown>
#7 0x55b0e2e202cc <unknown>
#8 0x55b0e2e01253 <unknown>
#9 0x55b0e2dd11c7 <unknown>
#10 0x55b0e2dd1b3e <unknown>
#11 0x55b0e306f27b <unknown>
#12 0x55b0e3073327 <unknown>
#13 0x55b0e305bdae <unknown>
#14 0x55b0e3073df2 <unknown>
#15 0x55b0e304074f <unknown>
#16 0x55b0e3098128 <unknown>
#17 0x55b0e30982fb <unknown>
#18 0x55b0e30a7f6c <unknown>
#19 0x7f0162f5bac3 <unknown>

Traceback (most recent call last):
  File "/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py", line 46, in <module>
    first_export.click()
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=125.0.6422.141)
Stacktrace:
#0 0x55b0e30a8e3a <unknown>
#1 0x55b0e2d922a1 <unknown>
#2 0x55b0e2ddf70f <unknown>
#3 0x55b0e2dd30ff <unknown>
#4 0x55b0e2e014b2 <unknown>
#5 0x55b0e2dd2a79 <unknown>
#6 0x55b0e2e0167e <unknown>
#7 0x55b0e2e202cc <unknown>
#8 0x55b0e2e01253 <unknown>
#9 0x55b0e2dd11c7 <unknown>
#10 0x55b0e2dd1b3e <unknown>
#11 0x55b0e306f27b <unknown>
#12 0x55b0e3073327 <unknown>
#13 0x55b0e305bdae <unknown>
#14 0x55b0e3073df2 <unknown>
#15 0x55b0e304074f <unknown>
#16 0x55b0e3098128 <unknown>
#17 0x55b0e30982fb <unknown>
#18 0x55b0e30a7f6c <unknown>
#19 0x7f0162f5bac3 <unknown>


INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
ERROR:root:Terjadi kesalahan: File tidak berhasil diunduh dalam batas waktu yang ditentukan.
Traceback (most recent call last):
  File "/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py", line 62, in <module>
    raise FileNotFoundError("File tidak berhasil diunduh dalam batas waktu yang ditentukan.")
FileNotFoundError: File tidak berhasil diunduh dalam batas waktu yang ditentukan.

INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
ERROR:root:Terjadi kesalahan: Message: element not interactable
  (Session info: chrome=125.0.6422.141)
Stacktrace:
#0 0x5603ac16fe3a <unknown>
#1 0x5603abe592a1 <unknown>
#2 0x5603abea670f <unknown>
#3 0x5603abe9a0ff <unknown>
#4 0x5603abec84b2 <unknown>
#5 0x5603abe99a79 <unknown>
#6 0x5603abec867e <unknown>
#7 0x5603abee72cc <unknown>
#8 0x5603abec8253 <unknown>
#9 0x5603abe981c7 <unknown>
#10 0x5603abe98b3e <unknown>
#11 0x5603ac13627b <unknown>
#12 0x5603ac13a327 <unknown>
#13 0x5603ac122dae <unknown>
#14 0x5603ac13adf2 <unknown>
#15 0x5603ac10774f <unknown>
#16 0x5603ac15f128 <unknown>
#17 0x5603ac15f2fb <unknown>
#18 0x5603ac16ef6c <unknown>
#19 0x7f2b80e81ac3 <unknown>

Traceback (most recent call last):
  File "/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py", line 46, in <module>
    first_export.click()
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=125.0.6422.141)
Stacktrace:
#0 0x5603ac16fe3a <unknown>
#1 0x5603abe592a1 <unknown>
#2 0x5603abea670f <unknown>
#3 0x5603abe9a0ff <unknown>
#4 0x5603abec84b2 <unknown>
#5 0x5603abe99a79 <unknown>
#6 0x5603abec867e <unknown>
#7 0x5603abee72cc <unknown>
#8 0x5603abec8253 <unknown>
#9 0x5603abe981c7 <unknown>
#10 0x5603abe98b3e <unknown>
#11 0x5603ac13627b <unknown>
#12 0x5603ac13a327 <unknown>
#13 0x5603ac122dae <unknown>
#14 0x5603ac13adf2 <unknown>
#15 0x5603ac10774f <unknown>
#16 0x5603ac15f128 <unknown>
#17 0x5603ac15f2fb <unknown>
#18 0x5603ac16ef6c <unknown>
#19 0x7f2b80e81ac3 <unknown>


INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
INFO:root:Received arguments: {"id": 26, "brand_id": 1, "market_place_id": 2, "type": "meta_cpas", "link": "https://adsmanager.facebook.com/adsmanager/reporting/view?act=197030438627900&business_id=141399696986824&event_source=SANITIZE_METRICS&global_scope_id=141399696986824&attribution_windows=default&breakdowns=days_1%2Cadset_name&empty_comparison_time_range=true&filter_set=had_delivery-STRING%1EEQUAL%1E%221%22&locked_dimensions=1&metrics=spend%2Ccatalog_segment_actions%3Aomni_view_content%2Ccatalog_segment_actions%3Aomni_add_to_cart%2Ccatalog_segment_actions%3Aomni_purchase%2Ccatalog_segment_value%3Aomni_purchase%2Cfrequency%2Cimpressions%2Cclicks%2Cctr&sort_spec=days_1~desc&time_range=2024-05-30_2024-06-06%2Clast_7d&breakdown_regrouping=1&nav_source=no_referrer", "scheduled_to_run": "2024-06-01 09:00:00", "status": 3, "message": "Traceback (most recent call last):\n  File \"/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py\", line 18, in <module>\n    task_data = json.loads(sys.argv[1])\n  File \"/usr/lib/python3.10/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib/python3.10/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib/python3.10/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n", "created_at": "2024-06-11T04:28:01.000000Z", "updated_at": "2024-06-11T06:03:02.000000Z"}
INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
INFO:root:Received arguments: {"id": 26, "brand_id": 1, "market_place_id": 2, "type": "meta_cpas", "link": "https://adsmanager.facebook.com/adsmanager/reporting/view?act=197030438627900&business_id=141399696986824&event_source=SANITIZE_METRICS&global_scope_id=141399696986824&attribution_windows=default&breakdowns=days_1%2Cadset_name&empty_comparison_time_range=true&filter_set=had_delivery-STRING%1EEQUAL%1E%221%22&locked_dimensions=1&metrics=spend%2Ccatalog_segment_actions%3Aomni_view_content%2Ccatalog_segment_actions%3Aomni_add_to_cart%2Ccatalog_segment_actions%3Aomni_purchase%2Ccatalog_segment_value%3Aomni_purchase%2Cfrequency%2Cimpressions%2Cclicks%2Cctr&sort_spec=days_1~desc&time_range=2024-05-30_2024-06-06%2Clast_7d&breakdown_regrouping=1&nav_source=no_referrer", "scheduled_to_run": "2024-06-01 09:00:00", "status": 3, "message": null, "created_at": "2024-06-11T04:28:01.000000Z", "updated_at": "2024-06-11T06:07:02.000000Z"}
INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
ERROR:root:Terjadi kesalahan: Message: element not interactable
  (Session info: chrome=125.0.6422.141)
Stacktrace:
#0 0x559588b31e3a <unknown>
#1 0x55958881b2a1 <unknown>
#2 0x55958886870f <unknown>
#3 0x55958885c0ff <unknown>
#4 0x55958888a4b2 <unknown>
#5 0x55958885ba79 <unknown>
#6 0x55958888a67e <unknown>
#7 0x5595888a92cc <unknown>
#8 0x55958888a253 <unknown>
#9 0x55958885a1c7 <unknown>
#10 0x55958885ab3e <unknown>
#11 0x559588af827b <unknown>
#12 0x559588afc327 <unknown>
#13 0x559588ae4dae <unknown>
#14 0x559588afcdf2 <unknown>
#15 0x559588ac974f <unknown>
#16 0x559588b21128 <unknown>
#17 0x559588b212fb <unknown>
#18 0x559588b30f6c <unknown>
#19 0x7f1116bd1ac3 <unknown>

Traceback (most recent call last):
  File "/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py", line 41, in <module>
    first_export.click()
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=125.0.6422.141)
Stacktrace:
#0 0x559588b31e3a <unknown>
#1 0x55958881b2a1 <unknown>
#2 0x55958886870f <unknown>
#3 0x55958885c0ff <unknown>
#4 0x55958888a4b2 <unknown>
#5 0x55958885ba79 <unknown>
#6 0x55958888a67e <unknown>
#7 0x5595888a92cc <unknown>
#8 0x55958888a253 <unknown>
#9 0x55958885a1c7 <unknown>
#10 0x55958885ab3e <unknown>
#11 0x559588af827b <unknown>
#12 0x559588afc327 <unknown>
#13 0x559588ae4dae <unknown>
#14 0x559588afcdf2 <unknown>
#15 0x559588ac974f <unknown>
#16 0x559588b21128 <unknown>
#17 0x559588b212fb <unknown>
#18 0x559588b30f6c <unknown>
#19 0x7f1116bd1ac3 <unknown>


INFO:root:Received arguments: {"id": 26, "brand_id": 1, "market_place_id": 2, "type": "meta_cpas", "link": "https://adsmanager.facebook.com/adsmanager/reporting/view?act=197030438627900&business_id=141399696986824&event_source=SANITIZE_METRICS&global_scope_id=141399696986824&attribution_windows=default&breakdowns=days_1%2Cadset_name&empty_comparison_time_range=true&filter_set=had_delivery-STRING%1EEQUAL%1E%221%22&locked_dimensions=1&metrics=spend%2Ccatalog_segment_actions%3Aomni_view_content%2Ccatalog_segment_actions%3Aomni_add_to_cart%2Ccatalog_segment_actions%3Aomni_purchase%2Ccatalog_segment_value%3Aomni_purchase%2Cfrequency%2Cimpressions%2Cclicks%2Cctr&sort_spec=days_1~desc&time_range=2024-05-30_2024-06-06%2Clast_7d&breakdown_regrouping=1&nav_source=no_referrer", "scheduled_to_run": "2024-06-01 09:00:00", "status": 3, "message": "Terjadi kesalahan: Message: element not interactable\n  (Session info: chrome=125.0.6422.141)\nStacktrace:\n#0 0x559588b31e3a <unknown>\n#1 0x55958881b2a1 <unknown>\n#2 0x55958886870f <unknown>\n#3 0x55958885c0ff <unknown>\n#4 0x55958888a4b2 <unknown>\n#5 0x55958885ba79 <unknown>\n#6 0x55958888a67e <unknown>\n#7 0x5595888a92cc <unknown>\n#8 0x55958888a253 <unknown>\n#9 0x55958885a1c7 <unknown>\n#10 0x55958885ab3e <unknown>\n#11 0x559588af827b <unknown>\n#12 0x559588afc327 <unknown>\n#13 0x559588ae4dae <unknown>\n#14 0x559588afcdf2 <unknown>\n#15 0x559588ac974f <unknown>\n#16 0x559588b21128 <unknown>\n#17 0x559588b212fb <unknown>\n#18 0x559588b30f6c <unknown>\n#19 0x7f1116bd1ac3 <unknown>\n\nTraceback (most recent call last):\n  File \"/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py\", line 41, in <module>\n    first_export.click()\n  File \"/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py\", line 94, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py\", line 395, in _execute\n    return self._parent.execute(command, params)\n  File \"/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.ElementNotInteractableException: Message: element not interactable\n  (Session info: chrome=125.0.6422.141)\nStacktrace:\n#0 0x559588b31e3a <unknown>\n#1 0x55958881b2a1 <unknown>\n#2 0x55958886870f <unknown>\n#3 0x55958885c0ff <unknown>\n#4 0x55958888a4b2 <unknown>\n#5 0x55958885ba79 <unknown>\n#6 0x55958888a67e <unknown>\n#7 0x5595888a92cc <unknown>\n#8 0x55958888a253 <unknown>\n#9 0x55958885a1c7 <unknown>\n#10 0x55958885ab3e <unknown>\n#11 0x559588af827b <unknown>\n#12 0x559588afc327 <unknown>\n#13 0x559588ae4dae <unknown>\n#14 0x559588afcdf2 <unknown>\n#15 0x559588ac974f <unknown>\n#16 0x559588b21128 <unknown>\n#17 0x559588b212fb <unknown>\n#18 0x559588b30f6c <unknown>\n#19 0x7f1116bd1ac3 <unknown>\n\n", "created_at": "2024-06-11T04:28:01.000000Z", "updated_at": "2024-06-11T06:31:01.000000Z"}
INFO:root:Received arguments: {"id": 26, "brand_id": 1, "market_place_id": 2, "type": "meta_cpas", "link": "https://adsmanager.facebook.com/adsmanager/reporting/view?act=197030438627900&business_id=141399696986824&event_source=SANITIZE_METRICS&global_scope_id=141399696986824&attribution_windows=default&breakdowns=days_1%2Cadset_name&empty_comparison_time_range=true&filter_set=had_delivery-STRING%1EEQUAL%1E%221%22&locked_dimensions=1&metrics=spend%2Ccatalog_segment_actions%3Aomni_view_content%2Ccatalog_segment_actions%3Aomni_add_to_cart%2Ccatalog_segment_actions%3Aomni_purchase%2Ccatalog_segment_value%3Aomni_purchase%2Cfrequency%2Cimpressions%2Cclicks%2Cctr&sort_spec=days_1~desc&time_range=2024-05-30_2024-06-06%2Clast_7d&breakdown_regrouping=1&nav_source=no_referrer", "scheduled_to_run": "2024-06-01 09:00:00", "status": 3, "message": "cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://127.0.0.1:8001/run-script", "created_at": "2024-06-11T04:28:01.000000Z", "updated_at": "2024-06-11T06:47:01.000000Z"}
INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
INFO:root:Received arguments: {"id": 26, "brand_id": 1, "market_place_id": 2, "type": "meta_cpas", "link": "https://adsmanager.facebook.com/adsmanager/reporting/view?act=197030438627900&business_id=141399696986824&event_source=SANITIZE_METRICS&global_scope_id=141399696986824&attribution_windows=default&breakdowns=days_1%2Cadset_name&empty_comparison_time_range=true&filter_set=had_delivery-STRING%1EEQUAL%1E%221%22&locked_dimensions=1&metrics=spend%2Ccatalog_segment_actions%3Aomni_view_content%2Ccatalog_segment_actions%3Aomni_add_to_cart%2Ccatalog_segment_actions%3Aomni_purchase%2Ccatalog_segment_value%3Aomni_purchase%2Cfrequency%2Cimpressions%2Cclicks%2Cctr&sort_spec=days_1~desc&time_range=2024-05-30_2024-06-06%2Clast_7d&breakdown_regrouping=1&nav_source=no_referrer", "scheduled_to_run": "2024-06-01 09:00:00", "status": 3, "message": null, "created_at": "2024-06-11T04:28:01.000000Z", "updated_at": "2024-06-11T06:48:01.000000Z"}
INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
INFO:root:Received arguments: {"id": 26, "brand_id": 1, "market_place_id": 2, "type": "meta_cpas", "link": "https://adsmanager.facebook.com/adsmanager/reporting/view?act=197030438627900&business_id=141399696986824&event_source=SANITIZE_METRICS&global_scope_id=141399696986824&attribution_windows=default&breakdowns=days_1%2Cadset_name&empty_comparison_time_range=true&filter_set=had_delivery-STRING%1EEQUAL%1E%221%22&locked_dimensions=1&metrics=spend%2Ccatalog_segment_actions%3Aomni_view_content%2Ccatalog_segment_actions%3Aomni_add_to_cart%2Ccatalog_segment_actions%3Aomni_purchase%2Ccatalog_segment_value%3Aomni_purchase%2Cfrequency%2Cimpressions%2Cclicks%2Cctr&sort_spec=days_1~desc&time_range=2024-05-30_2024-06-06%2Clast_7d&breakdown_regrouping=1&nav_source=no_referrer", "scheduled_to_run": "2024-06-01 09:00:00", "status": 3, "message": null, "created_at": "2024-06-11T04:28:01.000000Z", "updated_at": "2024-06-11T07:02:01.000000Z"}
INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
INFO:root:Received arguments: {"id": 26, "brand_id": 1, "market_place_id": 2, "type": "meta_cpas", "link": "https://adsmanager.facebook.com/adsmanager/reporting/view?act=197030438627900&business_id=141399696986824&event_source=SANITIZE_METRICS&global_scope_id=141399696986824&attribution_windows=default&breakdowns=days_1%2Cadset_name&empty_comparison_time_range=true&filter_set=had_delivery-STRING%1EEQUAL%1E%221%22&locked_dimensions=1&metrics=spend%2Ccatalog_segment_actions%3Aomni_view_content%2Ccatalog_segment_actions%3Aomni_add_to_cart%2Ccatalog_segment_actions%3Aomni_purchase%2Ccatalog_segment_value%3Aomni_purchase%2Cfrequency%2Cimpressions%2Cclicks%2Cctr&sort_spec=days_1~desc&time_range=2024-05-30_2024-06-06%2Clast_7d&breakdown_regrouping=1&nav_source=no_referrer", "scheduled_to_run": "2024-06-01 09:00:00", "status": 3, "message": null, "created_at": "2024-06-11T04:28:01.000000Z", "updated_at": "2024-06-11T07:04:01.000000Z"}
INFO:root:Received arguments: {"id": 26, "brand_id": 1, "market_place_id": 2, "type": "meta_cpas", "link": "https://adsmanager.facebook.com/adsmanager/reporting/view?act=197030438627900&business_id=141399696986824&event_source=SANITIZE_METRICS&global_scope_id=141399696986824&attribution_windows=default&breakdowns=days_1%2Cadset_name&empty_comparison_time_range=true&filter_set=had_delivery-STRING%1EEQUAL%1E%221%22&locked_dimensions=1&metrics=spend%2Ccatalog_segment_actions%3Aomni_view_content%2Ccatalog_segment_actions%3Aomni_add_to_cart%2Ccatalog_segment_actions%3Aomni_purchase%2Ccatalog_segment_value%3Aomni_purchase%2Cfrequency%2Cimpressions%2Cclicks%2Cctr&sort_spec=days_1~desc&time_range=2024-05-30_2024-06-06%2Clast_7d&breakdown_regrouping=1&nav_source=no_referrer", "scheduled_to_run": "2024-06-01 09:00:00", "status": 3, "message": "cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://127.0.0.1:8001/run-script", "created_at": "2024-06-11T04:28:01.000000Z", "updated_at": "2024-06-11T07:06:02.000000Z"}
INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
INFO:root:Received arguments: {"id": 26, "brand_id": 1, "market_place_id": 2, "type": "meta_cpas", "link": "https://adsmanager.facebook.com/adsmanager/reporting/view?act=197030438627900&business_id=141399696986824&event_source=SANITIZE_METRICS&global_scope_id=141399696986824&attribution_windows=default&breakdowns=days_1%2Cadset_name&empty_comparison_time_range=true&filter_set=had_delivery-STRING%1EEQUAL%1E%221%22&locked_dimensions=1&metrics=spend%2Ccatalog_segment_actions%3Aomni_view_content%2Ccatalog_segment_actions%3Aomni_add_to_cart%2Ccatalog_segment_actions%3Aomni_purchase%2Ccatalog_segment_value%3Aomni_purchase%2Cfrequency%2Cimpressions%2Cclicks%2Cctr&sort_spec=days_1~desc&time_range=2024-05-30_2024-06-06%2Clast_7d&breakdown_regrouping=1&nav_source=no_referrer", "scheduled_to_run": "2024-06-01 09:00:00", "status": 3, "message": null, "created_at": "2024-06-11T04:28:01.000000Z", "updated_at": "2024-06-11T07:08:02.000000Z"}
INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
INFO:root:Received arguments: {"id": 26, "brand_id": 1, "market_place_id": 2, "type": "meta_cpas", "link": "https://adsmanager.facebook.com/adsmanager/reporting/view?act=197030438627900&business_id=141399696986824&event_source=SANITIZE_METRICS&global_scope_id=141399696986824&attribution_windows=default&breakdowns=days_1%2Cadset_name&empty_comparison_time_range=true&filter_set=had_delivery-STRING%1EEQUAL%1E%221%22&locked_dimensions=1&metrics=spend%2Ccatalog_segment_actions%3Aomni_view_content%2Ccatalog_segment_actions%3Aomni_add_to_cart%2Ccatalog_segment_actions%3Aomni_purchase%2Ccatalog_segment_value%3Aomni_purchase%2Cfrequency%2Cimpressions%2Cclicks%2Cctr&sort_spec=days_1~desc&time_range=2024-05-30_2024-06-06%2Clast_7d&breakdown_regrouping=1&nav_source=no_referrer", "scheduled_to_run": "2024-06-01 09:00:00", "status": 3, "message": null, "created_at": "2024-06-11T04:28:01.000000Z", "updated_at": "2024-06-11T07:11:01.000000Z"}
INFO:root:Received arguments: {"id": 26, "brand_id": 1, "market_place_id": 2, "type": "meta_cpas", "link": "https://adsmanager.facebook.com/adsmanager/reporting/view?act=197030438627900&business_id=141399696986824&event_source=SANITIZE_METRICS&global_scope_id=141399696986824&attribution_windows=default&breakdowns=days_1%2Cadset_name&empty_comparison_time_range=true&filter_set=had_delivery-STRING%1EEQUAL%1E%221%22&locked_dimensions=1&metrics=spend%2Ccatalog_segment_actions%3Aomni_view_content%2Ccatalog_segment_actions%3Aomni_add_to_cart%2Ccatalog_segment_actions%3Aomni_purchase%2Ccatalog_segment_value%3Aomni_purchase%2Cfrequency%2Cimpressions%2Cclicks%2Cctr&sort_spec=days_1~desc&time_range=2024-05-30_2024-06-06%2Clast_7d&breakdown_regrouping=1&nav_source=no_referrer", "scheduled_to_run": "2024-06-01 09:00:00", "status": 3, "message": "cURL error 28: Operation timed out after 30002 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://127.0.0.1:8001/run-script", "created_at": "2024-06-11T04:28:01.000000Z", "updated_at": "2024-06-11T07:13:01.000000Z"}
INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
ERROR:root:Terjadi kesalahan: Message: unknown error: cannot connect to chrome at 127.0.0.1:58643
from chrome not reachable
Stacktrace:
#0 0x55b9f2826e3a <unknown>
#1 0x55b9f25102a1 <unknown>
#2 0x55b9f24fa96f <unknown>
#3 0x55b9f254a825 <unknown>
#4 0x55b9f25410b4 <unknown>
#5 0x55b9f258bb19 <unknown>
#6 0x55b9f257f253 <unknown>
#7 0x55b9f254f1c7 <unknown>
#8 0x55b9f254fb3e <unknown>
#9 0x55b9f27ed27b <unknown>
#10 0x55b9f27f1327 <unknown>
#11 0x55b9f27d9dae <unknown>
#12 0x55b9f27f1df2 <unknown>
#13 0x55b9f27be74f <unknown>
#14 0x55b9f2816128 <unknown>
#15 0x55b9f28162fb <unknown>
#16 0x55b9f2825f6c <unknown>
#17 0x7f877e119ac3 <unknown>

Traceback (most recent call last):
  File "/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py", line 30, in <module>
    driver = uc.Chrome(options=options)
  File "/home/rajab/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 49, in __init__
    super().__init__(
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 54, in __init__
    super().__init__(
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/home/rajab/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:58643
from chrome not reachable
Stacktrace:
#0 0x55b9f2826e3a <unknown>
#1 0x55b9f25102a1 <unknown>
#2 0x55b9f24fa96f <unknown>
#3 0x55b9f254a825 <unknown>
#4 0x55b9f25410b4 <unknown>
#5 0x55b9f258bb19 <unknown>
#6 0x55b9f257f253 <unknown>
#7 0x55b9f254f1c7 <unknown>
#8 0x55b9f254fb3e <unknown>
#9 0x55b9f27ed27b <unknown>
#10 0x55b9f27f1327 <unknown>
#11 0x55b9f27d9dae <unknown>
#12 0x55b9f27f1df2 <unknown>
#13 0x55b9f27be74f <unknown>
#14 0x55b9f2816128 <unknown>
#15 0x55b9f28162fb <unknown>
#16 0x55b9f2825f6c <unknown>
#17 0x7f877e119ac3 <unknown>


INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
2024-06-12 10:21:02,527 - DEBUG - getting release number from /last-known-good-versions-with-downloads.json
2024-06-12 10:41:00,677 - DEBUG - downloading from https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.55/linux64/chromedriver-linux64.zip
INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
INFO:root:Terjadi kesalahan: Message: session not created: cannot connect to chrome at 127.0.0.1:37571
from session not created: This version of ChromeDriver only supports Chrome version 126
Current browser version is 125.0.6422.141
Stacktrace:
#0 0x5646cdc7a6aa <unknown>
#1 0x5646cd95d0dc <unknown>
#2 0x5646cd998b8b <unknown>
#3 0x5646cd997d32 <unknown>
#4 0x5646cd98dcbc <unknown>
#5 0x5646cd9d8ef9 <unknown>
#6 0x5646cd9cc613 <unknown>
#7 0x5646cd99c4f7 <unknown>
#8 0x5646cd99ce4e <unknown>
#9 0x5646cdc4087b <unknown>
#10 0x5646cdc44921 <unknown>
#11 0x5646cdc2c36e <unknown>
#12 0x5646cdc45482 <unknown>
#13 0x5646cdc10ccf <unknown>
#14 0x5646cdc6a0a8 <unknown>
#15 0x5646cdc6a280 <unknown>
#16 0x5646cdc797dc <unknown>
#17 0x7fa9f5e9cac3 <unknown>

Traceback (most recent call last):
  File "/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py", line 30, in <module>
    driver = uc.Chrome(options=options)
  File "/home/rajab/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 49, in __init__
    super().__init__(
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 54, in __init__
    super().__init__(
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/home/rajab/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: cannot connect to chrome at 127.0.0.1:37571
from session not created: This version of ChromeDriver only supports Chrome version 126
Current browser version is 125.0.6422.141
Stacktrace:
#0 0x5646cdc7a6aa <unknown>
#1 0x5646cd95d0dc <unknown>
#2 0x5646cd998b8b <unknown>
#3 0x5646cd997d32 <unknown>
#4 0x5646cd98dcbc <unknown>
#5 0x5646cd9d8ef9 <unknown>
#6 0x5646cd9cc613 <unknown>
#7 0x5646cd99c4f7 <unknown>
#8 0x5646cd99ce4e <unknown>
#9 0x5646cdc4087b <unknown>
#10 0x5646cdc44921 <unknown>
#11 0x5646cdc2c36e <unknown>
#12 0x5646cdc45482 <unknown>
#13 0x5646cdc10ccf <unknown>
#14 0x5646cdc6a0a8 <unknown>
#15 0x5646cdc6a280 <unknown>
#16 0x5646cdc797dc <unknown>
#17 0x7fa9f5e9cac3 <unknown>


INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
INFO:root:Terjadi kesalahan: Message: session not created: cannot connect to chrome at 127.0.0.1:39471
from session not created: This version of ChromeDriver only supports Chrome version 126
Current browser version is 125.0.6422.141
Stacktrace:
#0 0x5631ae0976aa <unknown>
#1 0x5631add7a0dc <unknown>
#2 0x5631addb5b8b <unknown>
#3 0x5631addb4d32 <unknown>
#4 0x5631addaacbc <unknown>
#5 0x5631addf5ef9 <unknown>
#6 0x5631adde9613 <unknown>
#7 0x5631addb94f7 <unknown>
#8 0x5631addb9e4e <unknown>
#9 0x5631ae05d87b <unknown>
#10 0x5631ae061921 <unknown>
#11 0x5631ae04936e <unknown>
#12 0x5631ae062482 <unknown>
#13 0x5631ae02dccf <unknown>
#14 0x5631ae0870a8 <unknown>
#15 0x5631ae087280 <unknown>
#16 0x5631ae0967dc <unknown>
#17 0x7fd6f9e9aac3 <unknown>

Traceback (most recent call last):
  File "/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py", line 30, in <module>
    driver = uc.Chrome(options=options)
  File "/home/rajab/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 49, in __init__
    super().__init__(
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 54, in __init__
    super().__init__(
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/home/rajab/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: cannot connect to chrome at 127.0.0.1:39471
from session not created: This version of ChromeDriver only supports Chrome version 126
Current browser version is 125.0.6422.141
Stacktrace:
#0 0x5631ae0976aa <unknown>
#1 0x5631add7a0dc <unknown>
#2 0x5631addb5b8b <unknown>
#3 0x5631addb4d32 <unknown>
#4 0x5631addaacbc <unknown>
#5 0x5631addf5ef9 <unknown>
#6 0x5631adde9613 <unknown>
#7 0x5631addb94f7 <unknown>
#8 0x5631addb9e4e <unknown>
#9 0x5631ae05d87b <unknown>
#10 0x5631ae061921 <unknown>
#11 0x5631ae04936e <unknown>
#12 0x5631ae062482 <unknown>
#13 0x5631ae02dccf <unknown>
#14 0x5631ae0870a8 <unknown>
#15 0x5631ae087280 <unknown>
#16 0x5631ae0967dc <unknown>
#17 0x7fd6f9e9aac3 <unknown>


INFO:undetected_chromedriver.patcher:patching driver executable /home/rajab/.local/share/undetected_chromedriver/undetected_chromedriver
INFO:root:Terjadi kesalahan: Message: session not created: cannot connect to chrome at 127.0.0.1:47623
from session not created: This version of ChromeDriver only supports Chrome version 126
Current browser version is 108.0.5359.40
Stacktrace:
#0 0x55a9500206aa <unknown>
#1 0x55a94fd030dc <unknown>
#2 0x55a94fd3eb8b <unknown>
#3 0x55a94fd3dd32 <unknown>
#4 0x55a94fd33cbc <unknown>
#5 0x55a94fd7eef9 <unknown>
#6 0x55a94fd72613 <unknown>
#7 0x55a94fd424f7 <unknown>
#8 0x55a94fd42e4e <unknown>
#9 0x55a94ffe687b <unknown>
#10 0x55a94ffea921 <unknown>
#11 0x55a94ffd236e <unknown>
#12 0x55a94ffeb482 <unknown>
#13 0x55a94ffb6ccf <unknown>
#14 0x55a9500100a8 <unknown>
#15 0x55a950010280 <unknown>
#16 0x55a95001f7dc <unknown>
#17 0x7f655f341ac3 <unknown>

Traceback (most recent call last):
  File "/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py", line 30, in <module>
    driver = uc.Chrome(options=options)
  File "/home/rajab/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 49, in __init__
    super().__init__(
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 54, in __init__
    super().__init__(
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/home/rajab/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: cannot connect to chrome at 127.0.0.1:47623
from session not created: This version of ChromeDriver only supports Chrome version 126
Current browser version is 108.0.5359.40
Stacktrace:
#0 0x55a9500206aa <unknown>
#1 0x55a94fd030dc <unknown>
#2 0x55a94fd3eb8b <unknown>
#3 0x55a94fd3dd32 <unknown>
#4 0x55a94fd33cbc <unknown>
#5 0x55a94fd7eef9 <unknown>
#6 0x55a94fd72613 <unknown>
#7 0x55a94fd424f7 <unknown>
#8 0x55a94fd42e4e <unknown>
#9 0x55a94ffe687b <unknown>
#10 0x55a94ffea921 <unknown>
#11 0x55a94ffd236e <unknown>
#12 0x55a94ffeb482 <unknown>
#13 0x55a94ffb6ccf <unknown>
#14 0x55a9500100a8 <unknown>
#15 0x55a950010280 <unknown>
#16 0x55a95001f7dc <unknown>
#17 0x7f655f341ac3 <unknown>


INFO:root:Terjadi kesalahan: 'schedule_to_run'
Traceback (most recent call last):
  File "/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py", line 37, in <module>
    schedule_to_run = task_data['schedule_to_run']
KeyError: 'schedule_to_run'

INFO:root:Terjadi kesalahan: unconverted data remains:  09:00:00
Traceback (most recent call last):
  File "/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py", line 38, in <module>
    schedule_date = datetime.strptime(schedule_to_run, '%Y-%m-%d')
  File "/usr/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.10/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains:  09:00:00

INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Task Berjalan On Time...
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Terjadi kesalahan: Message: 
Stacktrace:
#0 0x56136909d6aa <unknown>
#1 0x561368d800dc <unknown>
#2 0x561368dcc931 <unknown>
#3 0x561368dcca21 <unknown>
#4 0x561368e11234 <unknown>
#5 0x561368def89d <unknown>
#6 0x561368e0e5c3 <unknown>
#7 0x561368def613 <unknown>
#8 0x561368dbf4f7 <unknown>
#9 0x561368dbfe4e <unknown>
#10 0x56136906387b <unknown>
#11 0x561369067921 <unknown>
#12 0x56136904f36e <unknown>
#13 0x561369068482 <unknown>
#14 0x561369033ccf <unknown>
#15 0x56136908d0a8 <unknown>
#16 0x56136908d280 <unknown>
#17 0x56136909c7dc <unknown>
#18 0x7fb744f37ac3 <unknown>

Traceback (most recent call last):
  File "/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py", line 58, in <module>
    click_select_timeframe = wait.until(EC.element_to_be_clickable((By.XPATH, "//*[contains(text(), 'Last 7 days')]")))
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x56136909d6aa <unknown>
#1 0x561368d800dc <unknown>
#2 0x561368dcc931 <unknown>
#3 0x561368dcca21 <unknown>
#4 0x561368e11234 <unknown>
#5 0x561368def89d <unknown>
#6 0x561368e0e5c3 <unknown>
#7 0x561368def613 <unknown>
#8 0x561368dbf4f7 <unknown>
#9 0x561368dbfe4e <unknown>
#10 0x56136906387b <unknown>
#11 0x561369067921 <unknown>
#12 0x56136904f36e <unknown>
#13 0x561369068482 <unknown>
#14 0x561369033ccf <unknown>
#15 0x56136908d0a8 <unknown>
#16 0x56136908d280 <unknown>
#17 0x56136909c7dc <unknown>
#18 0x7fb744f37ac3 <unknown>


INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat minimal satu hari, melakukan export data 14 hari terakhir
INFO:root:Terjadi kesalahan: Message: 
Stacktrace:
#0 0x56158635f6aa <unknown>
#1 0x5615860420dc <unknown>
#2 0x56158608e931 <unknown>
#3 0x56158608ea21 <unknown>
#4 0x5615860d3234 <unknown>
#5 0x5615860b189d <unknown>
#6 0x5615860d05c3 <unknown>
#7 0x5615860b1613 <unknown>
#8 0x5615860814f7 <unknown>
#9 0x561586081e4e <unknown>
#10 0x56158632587b <unknown>
#11 0x561586329921 <unknown>
#12 0x56158631136e <unknown>
#13 0x56158632a482 <unknown>
#14 0x5615862f5ccf <unknown>
#15 0x56158634f0a8 <unknown>
#16 0x56158634f280 <unknown>
#17 0x56158635e7dc <unknown>
#18 0x7fa434d69ac3 <unknown>

Traceback (most recent call last):
  File "/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py", line 45, in <module>
    click_select_timeframe = wait.until(EC.element_to_be_clickable((By.XPATH, "//*[contains(text(), 'Last 7 days')]")))
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x56158635f6aa <unknown>
#1 0x5615860420dc <unknown>
#2 0x56158608e931 <unknown>
#3 0x56158608ea21 <unknown>
#4 0x5615860d3234 <unknown>
#5 0x5615860b189d <unknown>
#6 0x5615860d05c3 <unknown>
#7 0x5615860b1613 <unknown>
#8 0x5615860814f7 <unknown>
#9 0x561586081e4e <unknown>
#10 0x56158632587b <unknown>
#11 0x561586329921 <unknown>
#12 0x56158631136e <unknown>
#13 0x56158632a482 <unknown>
#14 0x5615862f5ccf <unknown>
#15 0x56158634f0a8 <unknown>
#16 0x56158634f280 <unknown>
#17 0x56158635e7dc <unknown>
#18 0x7fa434d69ac3 <unknown>


INFO:root:Tanggal sudah terlewat minimal satu hari, melakukan export data 14 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Terjadi kesalahan: File tidak berhasil diunduh dalam batas waktu yang ditentukan.
Traceback (most recent call last):
  File "/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py", line 81, in <module>
    raise FileNotFoundError("File tidak berhasil diunduh dalam batas waktu yang ditentukan.")
FileNotFoundError: File tidak berhasil diunduh dalam batas waktu yang ditentukan.

WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff19b619450>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/37bede9aee13636eca2251579620fb7e
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff19b618b50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/37bede9aee13636eca2251579620fb7e
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff19b6194b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/37bede9aee13636eca2251579620fb7e
INFO:root:Terjadi kesalahan: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=126.0.6478.55)
Stacktrace:
#0 0x561ac4b846aa <unknown>
#1 0x561ac48670dc <unknown>
#2 0x561ac485ec70 <unknown>
#3 0x561ac484e772 <unknown>
#4 0x561ac484fdf2 <unknown>
#5 0x561ac484ea2d <unknown>
#6 0x561ac484e143 <unknown>
#7 0x561ac484e035 <unknown>
#8 0x561ac484bf76 <unknown>
#9 0x561ac484c47a <unknown>
#10 0x561ac4869b27 <unknown>
#11 0x561ac48f61f5 <unknown>
#12 0x561ac48d6872 <unknown>
#13 0x561ac48f55c3 <unknown>
#14 0x561ac48d6613 <unknown>
#15 0x561ac48a64f7 <unknown>
#16 0x561ac48a6e4e <unknown>
#17 0x561ac4b4a87b <unknown>
#18 0x561ac4b4e921 <unknown>
#19 0x561ac4b3636e <unknown>
#20 0x561ac4b4f482 <unknown>
#21 0x561ac4b1accf <unknown>
#22 0x561ac4b740a8 <unknown>
#23 0x561ac4b74280 <unknown>
#24 0x561ac4b837dc <unknown>
#25 0x7f20d25bdac3 <unknown>

Traceback (most recent call last):
  File "/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py", line 34, in <module>
    driver.get(url)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 355, in get
    self.execute(Command.GET, {"url": url})
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/home/rajab/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=126.0.6478.55)
Stacktrace:
#0 0x561ac4b846aa <unknown>
#1 0x561ac48670dc <unknown>
#2 0x561ac485ec70 <unknown>
#3 0x561ac484e772 <unknown>
#4 0x561ac484fdf2 <unknown>
#5 0x561ac484ea2d <unknown>
#6 0x561ac484e143 <unknown>
#7 0x561ac484e035 <unknown>
#8 0x561ac484bf76 <unknown>
#9 0x561ac484c47a <unknown>
#10 0x561ac4869b27 <unknown>
#11 0x561ac48f61f5 <unknown>
#12 0x561ac48d6872 <unknown>
#13 0x561ac48f55c3 <unknown>
#14 0x561ac48d6613 <unknown>
#15 0x561ac48a64f7 <unknown>
#16 0x561ac48a6e4e <unknown>
#17 0x561ac4b4a87b <unknown>
#18 0x561ac4b4e921 <unknown>
#19 0x561ac4b3636e <unknown>
#20 0x561ac4b4f482 <unknown>
#21 0x561ac4b1accf <unknown>
#22 0x561ac4b740a8 <unknown>
#23 0x561ac4b74280 <unknown>
#24 0x561ac4b837dc <unknown>
#25 0x7f20d25bdac3 <unknown>


INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Terjadi kesalahan: File tidak berhasil diunduh dalam batas waktu yang ditentukan.
Traceback (most recent call last):
  File "/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py", line 81, in <module>
    raise FileNotFoundError("File tidak berhasil diunduh dalam batas waktu yang ditentukan.")
FileNotFoundError: File tidak berhasil diunduh dalam batas waktu yang ditentukan.

WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe9dbad5450>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/036feec3a693b5197e89f93b14508fde
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe9dbad4b50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/036feec3a693b5197e89f93b14508fde
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe9dbad54b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/036feec3a693b5197e89f93b14508fde
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat minimal satu hari, melakukan export data 14 hari terakhir
INFO:root:Terjadi kesalahan: File tidak berhasil diunduh dalam batas waktu yang ditentukan.
Traceback (most recent call last):
  File "/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py", line 81, in <module>
    raise FileNotFoundError("File tidak berhasil diunduh dalam batas waktu yang ditentukan.")
FileNotFoundError: File tidak berhasil diunduh dalam batas waktu yang ditentukan.

WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbe1b4cd2d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f7fde5e1cd4e30a83c90585bca85ae4d
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbe1b4ccf40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f7fde5e1cd4e30a83c90585bca85ae4d
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbe1b4cd4e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f7fde5e1cd4e30a83c90585bca85ae4d
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat minimal satu hari, melakukan export data 14 hari terakhir
INFO:root:Terjadi kesalahan: File tidak berhasil diunduh dalam batas waktu yang ditentukan.
Traceback (most recent call last):
  File "/home/rajab/laravel/myproject/realco_dashboard/scripts/meta_cpas.py", line 81, in <module>
    raise FileNotFoundError("File tidak berhasil diunduh dalam batas waktu yang ditentukan.")
FileNotFoundError: File tidak berhasil diunduh dalam batas waktu yang ditentukan.

WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f75e8475450>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/35547635bdbe0a9cd332a7d182d1608a
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f75e8474c10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/35547635bdbe0a9cd332a7d182d1608a
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f75e84754b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/35547635bdbe0a9cd332a7d182d1608a
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
INFO:root:Tanggal sudah terlewat lebih dari 14 hari, melakukan export data 30 hari terakhir
